name: API Diff and Release
on:
  pull_request:
    types: [closed]
    paths:
      - 'api.yaml'
    branches:
      - main

jobs:
  diff-and-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Get API specs and generate JSON files
        run: |
          # Get the state before the PR (parent of merge commit)
          BEFORE_PR=$(git rev-parse ${{ github.event.pull_request.merge_commit_sha }}^1)
          echo "Using before-PR commit: $BEFORE_PR"
          
          git checkout $BEFORE_PR
          yq -o=json api.yaml > previous.json
          
          # Get the current merged state
          git checkout ${{ github.event.pull_request.merge_commit_sha }}
          yq -o=json api.yaml > current.json

      - name: Run API diff
        run: node scripts/api-diff.js

      - name: Install semantic-release                                                                                                      
        run: npm install semantic-release@22.0.7 @semantic-release/github@9.2.6

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout main
          git pull
          npx semantic-release
