name: GitHub Actions Testing

on:
  pull_request:

jobs:
  test_gha:
    name: Testing GitHub Actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Hello World
        id: hello-world
        run: |
          echo "Hello World"
